<a href="https://colab.research.google.com/github/areebaarshadqureshi/Data-Science-Journey-CampusX/blob/main/07-Pandas/03-Series-and-DataFrame-Functions/DataFrame_Functions_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [ ]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [ ]:
print("Average_Age:\n",titanic_df.groupby('Pclass')['Age'].mean())
print("\nTotal No of Missing Values:\n",titanic_df.groupby('Pclass')['Age'].apply(lambda x:x.isnull().sum()))

Average_Age:
 Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

Total No of Missing Values:
 Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [ ]:
data1=titanic_df.groupby('Pclass')['Embarked'].apply(lambda x:x.fillna(x.mode()[0]))
data1.groupby('Pclass').value_counts(ascending=True)

Pclass  Embarked
1       Q             2
        C            85
        S           129
2       Q             3
        C            17
        S           164
3       C            66
        Q            72
        S           353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [ ]:
emb=titanic_df.groupby(['Embarked','Pclass'])
round(emb['Fare'].mean(),2)

Embarked  Pclass
C         1         104.72
          2          25.36
          3          11.21
Q         1          90.00
          2          12.35
          3          11.18
S         1          70.36
          2          20.33
          3          14.64
Name: Fare, dtype: float64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

In [ ]:
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
fifa_df.head(3)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [ ]:
def z_normalization(group,cols_to_perform):
  for col in cols_to_perform:
    group[col]=(group[col]-group[col].mean())/group[col].std()
  return group

cols_to_perform=['Passes','Passes Completed','Attempted Line Breaks','Completed Line Breaks']
fifa_df.groupby('Team').apply(lambda group: z_normalization(group, cols_to_perform))

/tmp/ipython-input-2971664071.py:7: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  fifa_df.groupby('Team').apply(lambda group: z_normalization(group, cols_to_perform))

               Sl. No  Match No.       Team        Against Group  Goal  \
Team
Argentina 8         9          5  Argentina   Saudi Arabia     C     1
          46       47         24  Argentina         Mexico     C     2
          77       78         39  Argentina         Poland     C     2
          98       99         50  Argentina      Australia     C     2
          115     116         58  Argentina    Netherlands     C     2
...               ...        ...        ...            ...   ...   ...
Uruguay   63       64         32    Uruguay       Portugal     H     0
          89       90         45    Uruguay          Ghana     H     2
Wales     7         8          4      Wales  United States     B     1
          32       33         17      Wales           Iran     B     0
          68       69         35      Wales        England     B     0

               Possession (%)  Inside Penalty Area  Outside Penalty Area  \
Team
Argentina 8                51                    1                     0
          46               50                    1                     1
          77               67                    1                     1
          98               53                    2                     0
          115              44                    2                     0
...                       ...                  ...                   ...
Uruguay   63               35                    0                     0
          89               39                    2                     0
Wales     7                39                    1                     0
          32               51                    0                     0
          68               33                    0                     0

               Assists  ...  Fouls Against  Offsides    Passes  \
Team                    ...
Argentina 8          0  ...              7        10 -0.208138
          46         2  ...             15         2 -0.630447
          77         2  ...             11         0  1.685214
          98         1  ...              8         4  0.622403
          115        1  ...             18         2 -0.137753
...                ...  ...            ...       ...       ...
Uruguay   63         0  ...             16         0 -0.931702
          89         1  ...             11         2 -0.124867
Wales     7          0  ...             10         1 -0.054584
          32         0  ...              9         2  1.026174
          68         0  ...             16         1 -0.971590

               Passes Completed  Crosses  Crosses Completed  Corners  \
Team
Argentina 8           -0.157888       36                 15        9
          46          -0.574048       14                  2        4
          77           1.813757       22                  5        9
          98           0.592566        6                  1        1
          115         -0.253400       16                  4        8
...                         ...      ...                ...      ...
Uruguay   63          -0.894617       18                  5        2
          89          -0.184945       15                  4        2
Wales     7           -0.139325       15                  6        3
          32           1.062357       20                  5        2
          68          -0.923031        4                  1        1

               Free Kicks  Penalties Scored  Pts
Team
Argentina 8            21                 1    0
          46           23                 0    3
          77            5                 0    3
          98           15                 0    3
          115          30                 5    3
...                   ...               ...  ...
Uruguay   63           13                 0    0
          89           20                 0    3
Wales     7            15                 1    1
          32           12                 0    1
          68           10                 0    0

[128 rows x 38 columns]

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

In [ ]:
ipl=pd.read_csv('/content/ipl_deliveries.csv')
ipl.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [ ]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76757 entries, 0 to 76756
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 76757 non-null  int64
 1   Team               76757 non-null  object
 2   innings            76756 non-null  float64
 3   overs              76756 non-null  float64
 4   ballnumber         76756 non-null  float64
 5   batter             76756 non-null  object
 6   bowler             76756 non-null  object
 7   non-striker        76756 non-null  object
 8   extra_type         3919 non-null   object
 9   batsman_run        76756 non-null  float64
 10  extras_run         76756 non-null  float64
 11  total_run          76756 non-null  float64
 12  non_boundary       76756 non-null  float64
 13  isWicketDelivery   76756 non-null  float64
 14  player_out         3791 non-null   object
 15  kind               3791 non-null   object
 16  fielders_involved  2688 non-null   object
 17  BattingTeam        76756 non-null  object
 18  BowlingTeam        76756 non-null  object
dtypes: float64(8), int64(1), object(10)
memory usage: 11.1+ MB

In [ ]:
chasing=ipl[(ipl['innings']==2)]
balls_faced=chasing.groupby(['ID','batter']).size()
eligible_batters = balls_faced.groupby('batter').sum()
eligible_batters =eligible_batters [eligible_batters >=100].index
chasing_batsman=chasing[chasing['batter'].isin(eligible_batters)]
runs=chasing_batsman.groupby('batter')['batsman_run'].sum()
final=runs.sort_values(ascending=False).head(1)
balls=chasing_batsman.groupby('batter').size()
strike_rate=round((runs/balls)*100,2).sort_values(ascending=False).head(1)
print(f'Best Batsman who chased more runs:\n{final}')
print("🎯 Best Strike Rate while Chasing (Min 100 Balls Faced):")
print(strike_rate)

Best Batsman who chased more runs:
batter
V Kohli    3070
Name: batsman_run, dtype: int64
🎯 Best Strike Rate while Chasing (Min 100 Balls Faced):
batter
PJ Cummins    186.55
dtype: float64

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [ ]:
combo=ipl.groupby(['bowler','batter'])
combo['player_out'].count().sort_values(ascending=False).head(1)

bowler     batter
SP Narine  RG Sharma    8
Name: player_out, dtype: int64

In [ ]:
# Step 1: Filter rows where player_out is not null (i.e., actual dismissals)
dismissals = ipl[ipl['player_out'].notnull()]

# Step 2: Count dismissals per (bowler, batter) pair
dismissal_counts = dismissals.groupby(['bowler', 'batter'])['player_out'].count()

# Step 3: Sort and get the top pair
most_successful_pair = dismissal_counts.sort_values(ascending=False).head(1)
print(most_successful_pair)

bowler     batter
SP Narine  RG Sharma    8
Name: player_out, dtype: int64

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [ ]:
ipl.groupby(['batter','non-striker'])['batsman_run'].sum().sort_values(ascending=False).head(1)

batter          non-striker
AB de Villiers  V Kohli        1566
Name: batsman_run, dtype: int64

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [ ]:
pairs=ipl.groupby(['batter','non-striker'])['batsman_run'].agg(['sum','mean']).reset_index()
pairs.columns = ['batter', 'non-striker', 'Total_Runs', 'Average_Runs']

pairs_data=pd.DataFrame(pairs)
pairs_data

              batter      non-striker  Total_Runs  Average_Runs
0     A Ashish Reddy         A Mishra          19      1.266667
1     A Ashish Reddy  AA Jhunjhunwala           3      1.000000
2     A Ashish Reddy         CL White           3      1.000000
3     A Ashish Reddy     DB Ravi Teja           6      2.000000
4     A Ashish Reddy        DJG Sammy          26      1.444444
...              ...              ...         ...           ...
8057          Z Khan        S Aravind           0      0.000000
8058          Z Khan         S Nadeem           3      0.600000
8059          Z Khan       SL Malinga          17      2.125000
8060          Z Khan     SR Tendulkar           2      0.666667
8061          Z Khan        SS Tiwary          21      0.840000

[8062 rows x 4 columns]

In [ ]:
pairs_data.sort_values(by='Total_Runs',ascending=False,inplace=True)
pairs_data

              batter     non-striker  Total_Runs  Average_Runs
292   AB de Villiers         V Kohli        1566      1.518914
1283        CH Gayle         V Kohli        1508      1.499006
7493         V Kohli  AB de Villiers        1474      1.433852
1579       DA Warner        S Dhawan        1354      1.448128
7502         V Kohli        CH Gayle        1142      1.180972
...              ...             ...         ...           ...
978            B Lee         S Sohal           0      0.000000
970            B Lee   KC Sangakkara           0      0.000000
7380        TL Suman    Shoaib Ahmed           0      0.000000
7376        TL Suman        RP Singh           0      0.000000
7357       TK Curran     Shivam Mavi           0      0.000000

[8062 rows x 4 columns]

In [ ]:
ball_faced=ipl.groupby(['batter','non-striker']).size()
pairs_data['Ball_faced'] = pairs_data.apply(lambda row: ball_faced.get((row['batter'], row['non-striker']), 0), axis=1)
pairs_data

              batter     non-striker  Total_Runs  Average_Runs  Ball_faced
292   AB de Villiers         V Kohli        1566      1.518914        1031
1283        CH Gayle         V Kohli        1508      1.499006        1006
7493         V Kohli  AB de Villiers        1474      1.433852        1028
1579       DA Warner        S Dhawan        1354      1.448128         935
7502         V Kohli        CH Gayle        1142      1.180972         967
...              ...             ...         ...           ...         ...
978            B Lee         S Sohal           0      0.000000           2
970            B Lee   KC Sangakkara           0      0.000000           2
7380        TL Suman    Shoaib Ahmed           0      0.000000           1
7376        TL Suman        RP Singh           0      0.000000           1
7357       TK Curran     Shivam Mavi           0      0.000000           1

[8062 rows x 5 columns]

In [ ]:
pairs_data['Strike_rate']=round(pairs_data['Total_Runs']/pairs_data['Ball_faced']*100,2)
pairs_data.rename(columns={'batter':'Batsman 1','non-striker':'Batsman 2'},inplace=True)
pairs_data
pairs_data.set_index('Batsman 1')

,Batsman 2,Total_Runs,Average_Runs,Ball_faced,Strike_rate
Batsman 1,,,,,
AB de Villiers,V Kohli,1566,1.518914,1031,151.89
CH Gayle,V Kohli,1508,1.499006,1006,149.90
V Kohli,AB de Villiers,1474,1.433852,1028,143.39
DA Warner,S Dhawan,1354,1.448128,935,144.81
V Kohli,CH Gayle,1142,1.180972,967,118.10
...,...,...,...,...,...
B Lee,S Sohal,0,0.000000,2,0.00
B Lee,KC Sangakkara,0,0.000000,2,0.00
TL Suman,Shoaib Ahmed,0,0.000000,1,0.00
TL Suman,RP Singh,0,0.000000,1,0.00
TK Curran,Shivam Mavi,0,0.000000,1,0.00